theme: jekyll-theme-architect

title: Amazing Spider-Man
email: antoniow7783@aurorak12.org
description: >- # this means to ignore newlines until "baseurl:"
  A blog for the Amazing Spuder-Man
baseurl: "/Spider-Man" # the subpath of your site, e.g. /blog
url: "https://tonyjw2001.github.io/Amazing_Spider-Man/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: jekyll-theme-architect
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
